#!/usr/bin/env python3
"""Turn the 8-bit portraits (made in Magnific from the players' photos) into the Solitaire face-card images.

  python3 tools/make_portraits.py <folder with early.png jarman.png ngai.png wolleh.png dupree.png micot.png>

Each picture: the plain background (flood-filled from the edges) becomes transparent, the bust is cropped and sat on
the bottom edge of a square, shrunk to a real 64x64 pixel grid with a 24-colour palette, then blown up 4x with hard
pixels (so it stays crisp in every browser without relying on image-rendering). Writes src/portraits.js
(FR.data.images.mewc_<name>), which build.py loads after src/assets.js. Needs Pillow. The source pictures aren't
committed; only the finished 8-bit images are.
"""
import base64, io, os, sys
from collections import deque
from PIL import Image

NAMES = ['early', 'jarman', 'ngai', 'wolleh', 'dupree', 'micot']
GRID, SCALE, COLORS, TOL = 64, 4, 24, 38
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def find(folder, name):
    for ext in ('.png', '.jpg', '.jpeg', '.webp'):
        p = os.path.join(folder, name + ext)
        if os.path.exists(p): return p
    return None


def clear_background(im):
    """Flood-fill from every edge pixel that looks like the corner colour; those pixels become transparent."""
    im = im.convert('RGBA'); w, h = im.size; px = im.load()
    corners = [px[0, 0], px[w - 1, 0], px[0, h - 1], px[w - 1, h - 1]]
    bg = tuple(sorted(c[i] for c in corners)[1] for i in range(3))        # a robust corner colour
    near = lambda c: abs(c[0] - bg[0]) + abs(c[1] - bg[1]) + abs(c[2] - bg[2]) <= TOL
    seen = bytearray(w * h); q = deque()
    for x in range(w): q.extend([(x, 0), (x, h - 1)])
    for y in range(h): q.extend([(0, y), (w - 1, y)])
    while q:
        x, y = q.popleft()
        if x < 0 or y < 0 or x >= w or y >= h or seen[y * w + x]: continue
        seen[y * w + x] = 1
        if not near(px[x, y]): continue
        px[x, y] = (0, 0, 0, 0)
        q.extend([(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)])
    return im


def portrait(path):
    im = clear_background(Image.open(path))
    box = im.getbbox() or (0, 0, *im.size)
    im = im.crop(box)
    side = max(im.size)
    sq = Image.new('RGBA', (side, side), (0, 0, 0, 0))
    sq.paste(im, ((side - im.width) // 2, side - im.height), im)          # sit the bust on the bottom edge
    small = sq.resize((GRID, GRID), Image.BOX)
    alpha = small.getchannel('A').point(lambda a: 255 if a >= 128 else 0)
    rgb = Image.new('RGB', small.size, (255, 255, 255)); rgb.paste(small, mask=alpha)
    pal = rgb.quantize(colors=COLORS, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE).convert('RGBA')
    pal.putalpha(alpha)
    big = pal.resize((GRID * SCALE, GRID * SCALE), Image.NEAREST)
    buf = io.BytesIO(); big.save(buf, 'PNG', optimize=True)
    return buf.getvalue()


def main():
    if len(sys.argv) < 2: raise SystemExit(__doc__)
    folder = sys.argv[1]
    out = ['/* FRANK\'S COMPUTER - the Solitaire face-card portraits: 8-bit pictures of the MEWC players, made from their photos.',
           '   Generated by tools/make_portraits.py; do not edit by hand. */',
           '(() => { FR.data.images = FR.data.images || {};']
    for n in NAMES:
        src = find(folder, n)
        if not src: print(f'{n}: no picture, keeps the cartoon'); continue
        png = portrait(src)
        out.append(f"  FR.data.images.mewc_{n} = 'data:image/png;base64,{base64.b64encode(png).decode()}';")
        print(f'{n}: {len(png) // 1024} KB')
    out.append('})();\n')
    open(os.path.join(root, 'src', 'portraits.js'), 'w').write('\n'.join(out))
    print('wrote src/portraits.js')


if __name__ == '__main__':
    main()
