#!/usr/bin/env python3
"""Pack the AL PACKA website photos (made in Magnific) into src/salon_images.js.

  python3 tools/make_salon_images.py <folder with salon.png pompadour.png mullet.png beehive.png mohawk.png afro.png
                                              ceo.png fair.png wedding.png beforeafter.png>

Each photo is shrunk to at most 760 px wide and saved as a JPEG (quality 78), then embedded as
FR.data.images.sa_<name>, which src/apps/xp_salon.js shows. A missing photo is skipped (the page shows an empty
frame). Needs Pillow. The source photos aren't committed; only the packed JPEGs are.
"""
import base64, io, os, sys
from PIL import Image

NAMES = ['salon', 'pompadour', 'mullet', 'beehive', 'mohawk', 'afro', 'ceo', 'fair', 'wedding', 'beforeafter']
MAX_W, QUALITY = 760, 78
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def find(folder, name):
    for ext in ('.png', '.jpg', '.jpeg', '.webp'):
        p = os.path.join(folder, name + ext)
        if os.path.exists(p): return p
    return None


def pack(path):
    im = Image.open(path).convert('RGB')
    if im.width > MAX_W: im = im.resize((MAX_W, round(im.height * MAX_W / im.width)), Image.LANCZOS)
    buf = io.BytesIO(); im.save(buf, 'JPEG', quality=QUALITY, optimize=True, progressive=True)
    return buf.getvalue()


def main():
    if len(sys.argv) < 2: raise SystemExit(__doc__)
    out = ["/* FRANK'S COMPUTER - photos for the AL PACKA salon website (src/apps/xp_salon.js), made in Magnific.",
           '   Generated by tools/make_salon_images.py; do not edit by hand. */',
           '(() => { FR.data.images = FR.data.images || {};']
    total = 0
    for n in NAMES:
        src = find(sys.argv[1], n)
        if not src: print(f'{n}: no photo, the page shows an empty frame'); continue
        jpg = pack(src); total += len(jpg)
        out.append(f"  FR.data.images.sa_{n} = 'data:image/jpeg;base64,{base64.b64encode(jpg).decode()}';")
        print(f'{n}: {len(jpg) // 1024} KB')
    out.append('})();\n')
    open(os.path.join(root, 'src', 'salon_images.js'), 'w').write('\n'.join(out))
    print(f'wrote src/salon_images.js ({total // 1024} KB of photos)')


if __name__ == '__main__':
    main()
